package com.thistlewick.domain.event;

import com.thistlewick.domain.Task;
import java.time.LocalDateTime;
import java.util.Objects;

/**
 * Published when a {@link Task}'s due date changes.
 *
 * <p>Cornerstone of the Judgment Call: reminders derived from the old
 * due date are cancelled and regenerated by an observer.</p>
 */
public record TaskRescheduledEvent(
        Task task,
        LocalDateTime oldDueDate,
        LocalDateTime newDueDate,
        LocalDateTime occurredAt
) implements DomainEvent {

    public TaskRescheduledEvent {
        Objects.requireNonNull(task, "task required");
        Objects.requireNonNull(oldDueDate, "oldDueDate required");
        Objects.requireNonNull(newDueDate, "newDueDate required");
        Objects.requireNonNull(occurredAt, "occurredAt required");
    }
}